USE WAREHOUSE TRANSFER_ADO_ASSIGNMENT2_GROUP3;
USE DATABASE ADO_ASSIGNMENT2_GROUP3;
USE SCHEMA RAW_DATASET;

CREATE OR REPLACE TABLE CRIMES_PAST_YEAR_OCT_2024_CLEANED AS
SELECT 
    "CASE",
    -- Convert DATE_OF_OCCURRENCE to TIMESTAMP
    TO_TIMESTAMP(DATE_OF_OCCURRENCE, 'DD/MM/YYYY HH24:MI') AS DATE_OF_OCCURRENCE,
    -- Standardize text case for descriptions
    UPPER(BLOCK) AS BLOCK,
    IUCR,
    CASE 
        -- Normalize categories in PRIMARY_DESCRIPTION
        WHEN LOWER(PRIMARY_DESCRIPTION) LIKE '%theft%' THEN 'THEFT'
        WHEN LOWER(PRIMARY_DESCRIPTION) LIKE '%battery%' THEN 'BATTERY'
        WHEN LOWER(PRIMARY_DESCRIPTION) LIKE '%assault%' THEN 'ASSAULT'
        WHEN LOWER(PRIMARY_DESCRIPTION) LIKE '%damage%' THEN 'CRIMINAL DAMAGE'
        ELSE UPPER(PRIMARY_DESCRIPTION)
    END AS PRIMARY_DESCRIPTION,
    UPPER(SECONDARY_DESCRIPTION) AS SECONDARY_DESCRIPTION,
    UPPER(LOCATION_DESCRIPTION) AS LOCATION_DESCRIPTION,
    ARREST,
    DOMESTIC,
    BEAT,
    WARD,
    FBI_CD,
    X_COORDINATE,
    Y_COORDINATE,
    LATITUDE,
    LONGITUDE,
    LOCATION,
    -- Add derived columns
    EXTRACT(YEAR FROM TO_TIMESTAMP(DATE_OF_OCCURRENCE, 'DD/MM/YYYY HH24:MI')) AS YEAR,
    EXTRACT(MONTH FROM TO_TIMESTAMP(DATE_OF_OCCURRENCE, 'DD/MM/YYYY HH24:MI')) AS MONTH,
    EXTRACT(DAY FROM TO_TIMESTAMP(DATE_OF_OCCURRENCE, 'DD/MM/YYYY HH24:MI')) AS DAY,
    TO_CHAR(TO_TIMESTAMP(DATE_OF_OCCURRENCE, 'DD/MM/YYYY HH24:MI'), 'Day') AS DAY_OF_WEEK
FROM (
    -- Remove duplicate records
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY "CASE" ORDER BY DATE_OF_OCCURRENCE DESC) AS RN
    FROM CRIMES_PAST_YEAR_OCT_2024
) CLEANED_DUPLICATES
WHERE RN = 1
  AND "CASE" IS NOT NULL 
  AND IUCR IS NOT NULL 
  AND PRIMARY_DESCRIPTION IS NOT NULL;

-- Data Validation
SELECT *
FROM CRIMES_PAST_YEAR_OCT_2024_CLEANED
WHERE PRIMARY_DESCRIPTION IS NULL OR IUCR IS NULL;
