USE WAREHOUSE TRANSFER_ADO_ASSIGNMENT2_GROUP3;
USE DATABASE ADO_ASSIGNMENT2_GROUP3;
USE SCHEMA RAW_DATASET;

-- Task 1: Remove Duplicate Records
CREATE OR REPLACE TABLE CHICAGO_POLICE_DEPARTMENT_IUCR_CLEAN AS
SELECT *
FROM (
    SELECT 
        IUCR,
        PRIMARY_DESCRIPTION,
        SECONDARY_DESCRIPTION,
        INDEX_CODE,
        ACTIVE,
        ROW_NUMBER() OVER (PARTITION BY IUCR ORDER BY PRIMARY_DESCRIPTION DESC) AS RN
    FROM CHICAGO_POLICE_DEPARTMENT_IUCR
) CLEANED_DUPLICATES
WHERE RN = 1;

-- Task 2: Handle Missing Values
CREATE OR REPLACE TABLE CHICAGO_POLICE_DEPARTMENT_IUCR_CLEANED AS
SELECT 
    IUCR,
    COALESCE(PRIMARY_DESCRIPTION, 'Unknown') AS PRIMARY_DESCRIPTION,
    COALESCE(SECONDARY_DESCRIPTION, 'Unknown') AS SECONDARY_DESCRIPTION,
    COALESCE(INDEX_CODE, 'N') AS INDEX_CODE,
    COALESCE(ACTIVE, 'FALSE') AS ACTIVE
FROM CHICAGO_POLICE_DEPARTMENT_IUCR_CLEAN;

-- Task 3: Data Validation
SELECT *
FROM CHICAGO_POLICE_DEPARTMENT_IUCR_CLEANED
WHERE IUCR IS NULL OR PRIMARY_DESCRIPTION IS NULL;
